name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      fail_test:
        description: 'Fail test example'
        type: boolean
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      run: npx playwright test
      env:
        FAILURE: ${{ inputs.fail_test }}

    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: './ctrf/*.json'
      if: always()

    - name: Send results to Slack
      run: npx slack-ctrf results ctrf/ctrf-report.json -s "${{ secrets.SLACK_MENTION_USER_ID }} please hava a look"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TESTS_WEBHOOK_URL }}
      if: always()
